Error_code = {
    [10001]  = "消息频繁,已断开",
    [10002]  = "第一条消息必须是登录",
    [10003]  = "登录超时，5秒后重新发送登录消息（不必断开连接）",
    [10004]  = "正在加载数据，请勿频繁登录",
    [10005]  = "账号在线，是否顶号",
    [10006]  = "登录异常，请稍后再试",
    [10007]  = "需要排队",
    [10008]  = "未找到该渠道登录验证",
    [10010]  = "密码错误，请重新输入",
    [10011]  = "协议解析错误",
    [10012]  = "暂不支持RESPONSE",
    [10013]  = "被禁止通信",
    [10014]  = "找不到相关处理函数",
    [10015]  = "加载数据异常",
    [10016]  = "登录服务器异常",
    [10017]  = "未找到对应游戏",
    [10018]  = "进入房间失败",
    [10019]  = "已经在房间内",
}

local error_code = {
    success = 0,            --ok
    InvalidParam = 1            --参数有误
    DBError = 2                 --数据库异常
    account_already_exists = 3,            --账号已存在
    password_incorrect = 4,                --密码错误
    account_not_exists = 5,             --账号不存在
    SessionInvalid = 6          --session无效
    HardwareIncorrect = 7       --Hardware错误
    RoleAlreadyCreate = 8       --已经创建过角色了
    RoleNotExist = 9            --角色不存在
    CityNotExist = 10           --城市不存在
    CityNotMe = 11              --城市不是自己的
    UpError = 12                --升级失败
    GeneralNotFound = 13        --武将不存在
    GeneralNotMe = 14           --武将不是自己的
    ArmyNotFound = 15           --军队不存在
    ArmyNotMe = 15              --军队不是自己的
    ResNotEnough = 16           --资源不足
    OutArmyLimit = 17           --超过带兵限制
    ArmyBusy = 18               --军队再忙
    GeneralBusy = 19            --将领再忙
    CannotGiveUp = 20           --不能放弃
    BuildNotMe = 21             --领地不是自己的
    ArmyNotMain = 22            --军队没有主将
    UnReachable = 23            --不可到达
    PhysicalPowerNotEnough = 24 --体力不足
    DecreeNotEnough = 25        --政令不足
    GoldNotEnough = 26          --金币不足
    GeneralRepeat = 27          --重复上阵
    CostNotEnough = 28          --cost不足
    GeneralNoHas = 29           --没有该合成武将
    GeneralNoSame = 30          --合成武将非同名
    ArmyNotEnough = 31          --队伍数不足
    TongShuaiNotEnough = 32     --统帅不足
    GeneralStarMax = 33         --升级到最大星级
    UnionCreateError = 34       --联盟创建失败
    UnionNotFound = 35          --联盟不存在
    PermissionDenied = 36       --权限不足
    UnionAlreadyHas = 37        --已经有联盟
    UnionNotAllowExit = 38      --不允许退出
    ContentTooLong = 39         --内容太长
    NotBelongUnion = 40         --不属于该联盟
    PeopleIsFull = 41           --用户已满
    HasApply = 42               --已经申请过了
    BuildCanNotDefend = 43      --不能驻守
    BuildCanNotAttack = 44      --不能占领
    BuildMBSNotFound = 45       --没有军营
    BuildWarFree = 46           --免战中
    ArmyConscript = 47          --征兵中
    BuildGiveUpAlready = 48     --领地已经在放弃了
    CanNotBuildNew = 49         --不能再新建建筑在领地上
    CanNotTransfer = 50         --不能调兵
    HoldIsFull = 51             --坑位已满
    ArmyIsOutside = 52          --队伍在城外
    CanNotUpBuild = 53          --不能升级建筑
    CanNotDestroy = 54          --不能拆除建筑
    OutCollectTimesLimit = 55   --超过征收次数
    InCdCanNotOperate = 56      --cd内不能操作
    OutGeneralLimit = 57        --武将超过上限了
    NotHasJiShi = 58            --没有集市
    OutPosTagLimit = 59         --超过了收藏上限
    OutSkillLimit = 60          --超过了技能上限
    UpSkillError = 61           --装备技能失败
    DownSkillError = 62         --取下技能失败
    OutArmNotMatch = 63         --兵种不符
    PosNotSkill = 64            --该位置没有技能
    SkillLevelFull = 65         --技能等级已满
    RoleNameExist = 66          --昵称已经存在

}

return error_code